# Generated by Django 5.2.8 on 2025-12-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_essay'),
    ]

    operations = [
        migrations.RenameField(
            model_name='essay',
            old_name='submitted_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='grammar_errors',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='spelling_errors',
        ),
        migrations.AddField(
            model_name='essay',
            name='score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='essay',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
