# Generated by Django 5.2.8 on 2025-12-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_submitted_at_essay_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='grammar_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='spelling_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='total_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='essay',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='essay',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
