# Generated by Django 5.2.8 on 2025-12-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_essay_grammar_errors_essay_spelling_errors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='essays_pdfs/'),
        ),
    ]
