# Generated by Django 5.2.8 on 2025-12-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_essay_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='essay',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='essays/pdfs/'),
        ),
    ]
