# Generated by Django 5.2.8 on 2025-12-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_essay_is_approved_alter_essay_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
