# Generated by Django 5.2.8 on 2026-02-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_essay_is_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
